### ISSUE TITLE
`rf/reg-sub` does not support shortcuts of re-frame

### ISSUE THREAD

**Issue by rome-user** [ferdinand-beyer/refx#1]
Hello. Thank you for making this library. I realized that the following does not work
```clj
(rf/reg-sub
 ::example
 :-> ::example)
```
Instead we have to write
```clj
(rf/reg-sub
 ::example
 (fn [db _]
   (::example db)))
```

Would it be possible to add this? I may be able send a patch.

**Comment by ferdinand-beyer** [comment]
Are you sure? This should work, see:
https://github.com/ferdinand-beyer/refx/blob/main/core/src/refx/alpha.cljc#L78

If it does not, then there must be a bug.

**Comment by ferdinand-beyer** [comment]
Oh, you're right! Seems like I missed your use case for a 3-arg `reg-sub`, and this arity should probably delegate to "sugar parsing". Do you want to create a PR for this?
