### ISSUE TITLE
reg-sub doesn't work

### ISSUE THREAD

**Issue by markokocic** [ferdinand-beyer/refx#4]
I was trying to convert a hello-world project from re-frame to the latest released version of refx, and got the following error.

My subs.cljs file:
``` clojure
(ns todo.subs
  (:require
   [refx.alpha :as rf]))
   
(rf/reg-sub
 ::name
 (fn [db _]
   (:name db)))
```

shadow-cljs output:
```
 Resource: refx/subs.cljc:99:19
 Use of undeclared Var refx.subs/update-vals
```

**Comment by ferdinand-beyer** [comment]
Please update your `shadow-cljs` version. `update-vals` was introduced to ClojureScript in version v1.11.50.

**Comment by markokocic** [comment]
Yep, that was it. Thanks for the quick response.

I was under the impression that `npx shadow-cljs ...` always pulls the latest shadow-cljs version, but looks like I was wrong.
